### ISSUE TITLE
TikTok account creator with autoposting

### ISSUE THREAD

**Issue by Zaptified** [hendrikbgr/TikTok-Account-Creator#14]
Hello, would you be able to create a bot that creates accounts on TikTok, and posts on each account & repeat? I am in need of such program and it would be amazing if you could create this. If you can do this please message me on twitter @SatixFN! Have a great day.

**Comment by Jmmari20** [comment]
Have you achieved this?

**Comment by Zaptified** [comment]
Hello, I have purchased an account creator from jacov, I am waiting for poster to be created. Account is perfectly working. 
Here is his page:

https://github.com/jacovdev/TikTok-Account-Generator

**Comment by Jmmari20** [comment]
You responded quick 😂😂😂 does it actually work?

**Comment by Jmmari20** [comment]
And can this be done on Mac?

**Comment by Zaptified** [comment]
I got an email from your response lol. I don't think it works on mac but you can download oracle vm virtualbox and create a windows virtual machine and just run it on there.

**Comment by Zaptified** [comment]
> Jmmari20

and yes it works he will show you
